apiVersion: garage.rottler.io/v1alpha1
kind: GarageCluster
metadata:
  labels:
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/managed-by: kustomize
  name: garagecluster-sample
spec:
  replicationFactor: 3
  nodePools:
    - name: default
      replicas: 3
      storage:
        data: { size: 1Ti, storageClass: bulk }
        meta: { size: 5Gi, storageClass: fast }
