apiVersion: garage.rottler.io/v1alpha1
kind: GarageKey
metadata:
  labels:
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/managed-by: kustomize
  name: garagekey-sample
spec:
  # TODO(user): Add fields here
