apiVersion: garage.rottler.io/v1alpha1
kind: GarageBucket
metadata:
  labels:
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/managed-by: kustomize
  name: garagebucket-sample
spec:
  # TODO(user): Add fields here
