/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// GarageImage selects the Garage container image to run.
type GarageImage struct {
	// repository is the container image repository.
	// +kubebuilder:default="dxflrs/amd64_garage"
	// +optional
	Repository string `json:"repository,omitempty"`

	// tag is the image tag. Pinned by the user; defaulted by the operator if omitted.
	// +kubebuilder:default="v2.0.0"
	// +optional
	Tag string `json:"tag,omitempty"`
}

// SecretBootstrapMode controls whether a secret value is generated by the operator
// or supplied by the user.
// +kubebuilder:validation:Enum=Generate;Provided
type SecretBootstrapMode string

const (
	// SecretBootstrapGenerate makes the operator generate the secret into a Secret it owns.
	SecretBootstrapGenerate SecretBootstrapMode = "Generate"
	// SecretBootstrapProvided makes the operator read the secret from a user-supplied Secret.
	SecretBootstrapProvided SecretBootstrapMode = "Provided"
)

// SecretKeySelector points at a single key within a Secret.
type SecretKeySelector struct {
	// name is the Secret name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// key is the key within the Secret holding the value.
	// +kubebuilder:validation:Required
	Key string `json:"key"`
}

// SecretBootstrap describes how a sensitive value (admin token, RPC secret) is sourced.
// +kubebuilder:validation:XValidation:rule="!has(self.mode) || self.mode != 'Provided' || has(self.secretRef)",message="secretRef is required when mode is Provided"
type SecretBootstrap struct {
	// mode selects Generate (operator-managed) or Provided (user-supplied via secretRef).
	// +kubebuilder:default=Generate
	// +optional
	Mode SecretBootstrapMode `json:"mode,omitempty"`

	// secretRef is the Secret to read when mode is Provided.
	// +optional
	SecretRef *SecretKeySelector `json:"secretRef,omitempty"`
}

// StorageSpec describes a single persistent volume (data or metadata) for a node pool.
type StorageSpec struct {
	// size is the requested volume size. For the data volume this also derives the
	// node's Garage layout capacity.
	// +kubebuilder:validation:Required
	Size resource.Quantity `json:"size"`

	// storageClass is the StorageClass for the volume; the cluster default is used if omitted.
	// +optional
	StorageClass *string `json:"storageClass,omitempty"`
}

// NodePoolStorage groups the data and metadata volumes for a node pool.
type NodePoolStorage struct {
	// data is the bulk object-storage volume. Its size derives the node's layout capacity.
	// +kubebuilder:validation:Required
	Data StorageSpec `json:"data"`

	// meta is the metadata-database volume.
	// +kubebuilder:validation:Required
	Meta StorageSpec `json:"meta"`
}

// NodePool is a set of identically-configured Garage nodes backed by one StatefulSet.
// Each pool maps to a single Garage zone.
type NodePool struct {
	// name uniquely identifies the pool within the cluster (used in child resource names).
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
	Name string `json:"name"`

	// replicas is the number of Garage nodes in the pool.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Required
	Replicas int32 `json:"replicas"`

	// zone is the Garage layout zone for this pool. Defaults to the pool name if omitted.
	// Ignored when zoneFrom is set.
	// +optional
	Zone string `json:"zone,omitempty"`

	// zoneFrom derives each node's Garage zone from this label on the Kubernetes Node the
	// pod is scheduled on, letting one pool spread its replicas across failure domains. When
	// set it takes precedence over zone, and the operator spreads the pool's pods across the
	// label's values (a default topology-spread constraint). Every Node a pod lands on must
	// carry the label, or that node defers until it does.
	// +optional
	ZoneFrom string `json:"zoneFrom,omitempty"`

	// storage configures the data and metadata volumes.
	// +kubebuilder:validation:Required
	Storage NodePoolStorage `json:"storage"`

	// resources sets the Garage container resource requirements.
	// +optional
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// nodeSelector constrains pods to nodes matching these labels.
	// +optional
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// tolerations allow pods to schedule onto tainted nodes.
	// +optional
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`

	// affinity sets pod scheduling affinity/anti-affinity.
	// +optional
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
}

// ServiceConfig configures how a client-facing endpoint is exposed.
type ServiceConfig struct {
	// type is the Kubernetes Service type for the endpoint.
	// +kubebuilder:default=ClusterIP
	// +optional
	Type corev1.ServiceType `json:"type,omitempty"`
}

// ServicesConfig groups the client-facing Service exposure. The admin API is
// intentionally not exposed: it is reached only over per-pod headless DNS, since some
// admin operations are node-local and load balancing would route to a random node.
type ServicesConfig struct {
	// s3Api exposes the S3 API endpoint.
	// +optional
	S3Api ServiceConfig `json:"s3Api,omitempty"`

	// web exposes the static website endpoint.
	// +optional
	Web ServiceConfig `json:"web,omitempty"`
}

// MetricsConfig configures Prometheus scraping of the cluster's per-node Garage metrics.
// Garage exposes Prometheus-format metrics on each node's admin endpoint. Because those
// metrics are per-node — like the admin operations that keep the admin port headless-only —
// the operator scrapes every pod directly: when enabled it creates a PodMonitor (Prometheus
// Operator, monitoring.coreos.com/v1) targeting the pods' admin port. The PodMonitor is an
// implementation detail; if the Prometheus Operator CRDs are not installed the operator
// reports this and otherwise does nothing.
type MetricsConfig struct {
	// enabled turns on Prometheus scraping of the cluster's Garage nodes.
	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// interval is the Prometheus scrape interval (a Prometheus duration such as "30s" or
	// "1m"). The Prometheus default is used if omitted.
	// +kubebuilder:validation:Pattern="^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$"
	// +optional
	Interval string `json:"interval,omitempty"`

	// labels are extra labels stamped on the generated scrape config so a Prometheus
	// instance's selector can pick it up.
	// +optional
	Labels map[string]string `json:"labels,omitempty"`
}

// S3ApiConfig configures the Garage S3 API endpoint.
type S3ApiConfig struct {
	// region is the S3 region name advertised by Garage.
	// +kubebuilder:default="garage"
	// +optional
	Region string `json:"region,omitempty"`

	// rootDomain is the DNS suffix for virtual-hosted-style bucket access (e.g. ".s3.garage.tld").
	// +optional
	RootDomain string `json:"rootDomain,omitempty"`
}

// S3WebConfig configures the Garage static website endpoint.
type S3WebConfig struct {
	// rootDomain is the DNS suffix for website bucket access (e.g. ".web.garage.tld").
	// +optional
	RootDomain string `json:"rootDomain,omitempty"`
}

// S3Config groups the S3 API and website settings.
type S3Config struct {
	// api configures the S3 API endpoint.
	// +optional
	Api S3ApiConfig `json:"api,omitempty"`

	// web configures the static website endpoint.
	// +optional
	Web S3WebConfig `json:"web,omitempty"`
}

// GarageDBEngine selects the Garage metadata database engine.
// +kubebuilder:validation:Enum=lmdb;sqlite;fjall
type GarageDBEngine string

// GarageConsistencyMode selects the Garage read/write consistency guarantees.
// +kubebuilder:validation:Enum=consistent;degraded;dangerous
type GarageConsistencyMode string

// ZoneRedundancyMode selects how partitions are replicated across zones.
// +kubebuilder:validation:Enum=Maximum;AtLeast
type ZoneRedundancyMode string

const (
	// ZoneRedundancyMaximum replicates each partition across as many distinct zones as
	// possible (up to the replication factor) — Garage's default.
	ZoneRedundancyMaximum ZoneRedundancyMode = "Maximum"
	// ZoneRedundancyAtLeast replicates each partition across at least AtLeast distinct zones.
	ZoneRedundancyAtLeast ZoneRedundancyMode = "AtLeast"
)

// ZoneRedundancy controls how many distinct zones each data partition is replicated across.
// +kubebuilder:validation:XValidation:rule="!has(self.mode) || self.mode != 'AtLeast' || (has(self.atLeast) && self.atLeast >= 1)",message="atLeast must be set (>= 1) when mode is AtLeast"
type ZoneRedundancy struct {
	// mode is Maximum (spread across as many zones as possible) or AtLeast.
	// +kubebuilder:default=Maximum
	// +optional
	Mode ZoneRedundancyMode `json:"mode,omitempty"`

	// atLeast is the minimum number of distinct zones each partition must span. Required when
	// mode is AtLeast; ignored otherwise. Must not exceed the number of zones in the layout.
	// +kubebuilder:validation:Minimum=1
	// +optional
	AtLeast int `json:"atLeast,omitempty"`
}

// GarageClusterSpec defines the desired state of GarageCluster.
type GarageClusterSpec struct {
	// image selects the Garage container image.
	// +optional
	Image GarageImage `json:"image,omitempty"`

	// dbEngine selects the metadata database engine. Immutable once set: the Admin API
	// exposes no way to convert a live cluster's engine, so changing it is rejected.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#db_engine
	// +kubebuilder:default=lmdb
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="dbEngine is immutable"
	// +optional
	DBEngine GarageDBEngine `json:"dbEngine,omitempty"`

	// blockSize is the block size in bytes for stored objects.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#block_size
	// +kubebuilder:default=1048576
	// +kubebuilder:validation:Minimum=1
	// +optional
	BlockSize int64 `json:"blockSize,omitempty"`

	// replicationFactor is the Garage replication_factor. Immutable once set; changing it on
	// a live cluster risks data loss, so it is rejected.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#replication_factor
	// +kubebuilder:default=3
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="replicationFactor is immutable"
	// +optional
	ReplicationFactor int32 `json:"replicationFactor,omitempty"`

	// consistencyMode selects the read/write consistency guarantees.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#consistency_mode
	// +kubebuilder:default=consistent
	// +optional
	ConsistencyMode GarageConsistencyMode `json:"consistencyMode,omitempty"`

	// compressionLevel is the zstd compression level for stored blocks.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#compression_level
	// +kubebuilder:default=1
	// +optional
	CompressionLevel int32 `json:"compressionLevel,omitempty"`

	// metadataAutoSnapshotInterval, when set (e.g. "6h"), makes Garage snapshot its
	// metadata DB at that interval. Empty disables snapshots.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#metadata_auto_snapshot_interval
	// +optional
	MetadataAutoSnapshotInterval string `json:"metadataAutoSnapshotInterval,omitempty"`

	// nodePools defines one or more pools of Garage nodes. Each pool becomes a StatefulSet.
	// A pool maps to a single Garage zone unless it sets zoneFrom, which derives a per-node
	// zone from the Node each pod runs on.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +listType=map
	// +listMapKey=name
	NodePools []NodePool `json:"nodePools"`

	// zoneRedundancy controls how many distinct zones each partition replicates across
	// (cross-zone replication). Defaults to Maximum.
	// +optional
	ZoneRedundancy *ZoneRedundancy `json:"zoneRedundancy,omitempty"`

	// adminToken configures the Admin API token bootstrap.
	// +optional
	AdminToken SecretBootstrap `json:"adminToken,omitempty"`

	// rpcSecret configures the inter-node RPC secret bootstrap.
	// +optional
	RpcSecret SecretBootstrap `json:"rpcSecret,omitempty"`

	// referencePolicy restricts which namespaces may host GarageBucket / GarageKey
	// resources that target this cluster via clusterRef. When omitted, any namespace
	// may reference the cluster (the default, unrestricted behavior). The cluster's
	// own namespace is always allowed.
	// +optional
	ReferencePolicy *ReferencePolicy `json:"referencePolicy,omitempty"`

	// services configures exposure of the S3 and web endpoints.
	// +optional
	Services ServicesConfig `json:"services,omitempty"`

	// metrics configures Prometheus scraping of the cluster's per-node Garage metrics.
	// +optional
	Metrics MetricsConfig `json:"metrics,omitempty"`

	// s3 configures the S3 API and website settings.
	// +optional
	S3 S3Config `json:"s3,omitempty"`
}

// ReferencePolicy declares which namespaces may host GarageBucket / GarageKey
// resources that reference this cluster. A reference is permitted when its namespace
// is the cluster's own namespace, OR is listed in allowedNamespaces, OR matches
// namespaceSelector. An empty policy ({}) therefore permits only the cluster's own
// namespace.
type ReferencePolicy struct {
	// allowedNamespaces lists namespace names permitted to reference this cluster.
	// +optional
	// +listType=set
	AllowedNamespaces []string `json:"allowedNamespaces,omitempty"`

	// namespaceSelector permits any namespace whose labels match this selector.
	// It is OR-ed with allowedNamespaces.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`
}

// LayoutNodeStatus echoes one node's role in the applied Garage layout.
type LayoutNodeStatus struct {
	// nodeId is the Garage node identifier (its public key).
	NodeID string `json:"nodeId"`

	// pod is the Kubernetes Pod backing the node.
	Pod string `json:"pod"`

	// zone is the Garage layout zone assigned to the node.
	Zone string `json:"zone"`

	// capacity is the layout capacity assigned to the node, derived from storage.data.size.
	Capacity resource.Quantity `json:"capacity"`

	// role is the node's layout role (e.g. active).
	Role string `json:"role"`
}

// LayoutStatus reports the applied Garage cluster layout.
type LayoutStatus struct {
	// version is the applied Garage layout version.
	Version int64 `json:"version"`

	// nodes lists the per-node layout assignments.
	// +listType=atomic
	// +optional
	Nodes []LayoutNodeStatus `json:"nodes,omitempty"`
}

// HealthStatus mirrors Garage's GetClusterHealth response.
type HealthStatus struct {
	// status is one of healthy, degraded, or unavailable.
	Status string `json:"status"`

	// connectedNodes is the number of nodes currently connected.
	ConnectedNodes int `json:"connectedNodes"`

	// knownNodes is the number of nodes known to the cluster.
	KnownNodes int `json:"knownNodes"`

	// partitionsQuorum is the "<withQuorum>/<total>" partition quorum ratio.
	PartitionsQuorum string `json:"partitionsQuorum"`

	// partitionsAllOk is the "<fullyReplicated>/<total>" ratio of partitions connected to
	// all of their responsible storage nodes. When the two numbers match, the cluster is
	// fully re-replicated — the signal the storage migration waits for before it destroys
	// and recreates a node's volumes.
	PartitionsAllOk string `json:"partitionsAllOk"`
}

// EndpointsStatus reports the resolved client-facing endpoints.
type EndpointsStatus struct {
	// s3Api is the S3 API endpoint URL.
	// +optional
	S3Api string `json:"s3Api,omitempty"`

	// web is the website endpoint URL.
	// +optional
	Web string `json:"web,omitempty"`
}

// SnapshotStatus reports the outcome of the most recent operator-triggered metadata snapshot.
type SnapshotStatus struct {
	// observedTrigger is the garage.rottler.io/snapshot annotation value last acted on.
	// A snapshot runs once when this value changes; bumping it requests another.
	ObservedTrigger string `json:"observedTrigger"`

	// time is when the snapshot was requested.
	Time metav1.Time `json:"time"`

	// result is Succeeded, Partial (some nodes failed), or Failed (all nodes failed).
	Result string `json:"result"`

	// message summarizes the per-node outcome.
	// +optional
	Message string `json:"message,omitempty"`
}

// RepairStatus reports the most recent operator-triggered repair operation.
type RepairStatus struct {
	// observedTrigger is the garage.rottler.io/repair annotation value last acted on.
	// A repair launches once when this value changes; bumping it (e.g. "blocks@2") relaunches.
	ObservedTrigger string `json:"observedTrigger"`

	// type is the repair type that was launched.
	Type string `json:"type"`

	// time is when the repair was launched.
	Time metav1.Time `json:"time"`

	// state is Launched, Running, Done, or Failed. Running/Done are best-effort, derived from
	// Garage's background-worker activity, which may reflect unrelated maintenance.
	State string `json:"state"`

	// progress is a free-form summary of the active background workers, while any are running.
	// +optional
	Progress string `json:"progress,omitempty"`
}

// MaintenanceStatus records the most recent operator-triggered day-2 maintenance actions
// (metadata snapshot, repair). Both are one-shot actions requested via annotations; this block
// reports their outcome and tracks the trigger value last acted on so a repeated value is not
// re-run.
type MaintenanceStatus struct {
	// snapshot reports the most recent metadata-snapshot request.
	// +optional
	Snapshot *SnapshotStatus `json:"snapshot,omitempty"`

	// repair reports the most recent repair operation.
	// +optional
	Repair *RepairStatus `json:"repair,omitempty"`
}

// StorageMigrationPhase is the stage the node currently being migrated is in.
// +kubebuilder:validation:Enum=Draining;AwaitingReplication;RecreatingVolume;AwaitingRejoin
type StorageMigrationPhase string

const (
	// StorageMigrationDraining is removing the node from the layout so Garage redistributes
	// its data to the remaining replicas.
	StorageMigrationDraining StorageMigrationPhase = "Draining"
	// StorageMigrationAwaitingReplication is waiting for the drain to fully re-replicate
	// (every partition connected to all its responsible nodes) before destroying the volume.
	StorageMigrationAwaitingReplication StorageMigrationPhase = "AwaitingReplication"
	// StorageMigrationRecreatingVolume is recreating the node's PVCs at the new spec.
	StorageMigrationRecreatingVolume StorageMigrationPhase = "RecreatingVolume"
	// StorageMigrationAwaitingRejoin is waiting for the recreated node to rejoin the layout
	// and refill from replicas before the next node is migrated.
	StorageMigrationAwaitingRejoin StorageMigrationPhase = "AwaitingRejoin"
)

// StorageMigrationStatus reports an in-progress storage migration (PLAN.md §4.5). A change
// to a pool's volume sizes that the in-place path cannot serve — a shrink, or a grow on a
// StorageClass that forbids expansion — is carried out by draining one node at a time,
// recreating its volumes at the new spec, and refilling it from replicas. This block is
// operator-owned reporting, present only while a migration is underway.
type StorageMigrationStatus struct {
	// pool is the node pool being migrated.
	Pool string `json:"pool"`

	// ordinal is the StatefulSet ordinal of the node currently being migrated.
	Ordinal int32 `json:"ordinal"`

	// phase is the stage the current node is in.
	Phase StorageMigrationPhase `json:"phase"`

	// message is a human-readable summary of the current step.
	// +optional
	Message string `json:"message,omitempty"`
}

// GarageClusterStatus defines the observed state of GarageCluster.
type GarageClusterStatus struct {
	// conditions represent the current state of the GarageCluster resource.
	// Known types: Ready, WorkloadReady, PeersConnected, LayoutApplied, LayoutChangePending.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// observedGeneration is the generation most recently reconciled into status.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// layout reports the applied Garage cluster layout.
	// +optional
	Layout *LayoutStatus `json:"layout,omitempty"`

	// health mirrors Garage's cluster health.
	// +optional
	Health *HealthStatus `json:"health,omitempty"`

	// endpoints reports the resolved client-facing endpoints.
	// +optional
	Endpoints *EndpointsStatus `json:"endpoints,omitempty"`

	// maintenance reports operator-triggered metadata snapshot and repair operations.
	// +optional
	Maintenance *MaintenanceStatus `json:"maintenance,omitempty"`

	// storageMigration reports an in-progress storage migration. Present only while a
	// volume change that cannot be served in place is being rolled through the pool.
	// +optional
	StorageMigration *StorageMigrationStatus `json:"storageMigration,omitempty"`

	// adminTokenSecret names the Secret holding the Admin API token.
	// +optional
	AdminTokenSecret string `json:"adminTokenSecret,omitempty"`

	// rpcTokenSecret names the Secret holding the RPC secret.
	// +optional
	RpcTokenSecret string `json:"rpcTokenSecret,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Layout",type=integer,JSONPath=".status.layout.version"
// +kubebuilder:printcolumn:name="Health",type=string,JSONPath=".status.health.status"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

// GarageCluster is the Schema for the garageclusters API
type GarageCluster struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of GarageCluster
	// +required
	Spec GarageClusterSpec `json:"spec"`

	// status defines the observed state of GarageCluster
	// +optional
	Status GarageClusterStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// GarageClusterList contains a list of GarageCluster
type GarageClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []GarageCluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &GarageCluster{}, &GarageClusterList{})
		return nil
	})
}
