/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// GarageImage selects the Garage container image to run.
type GarageImage struct {
	// repository is the container image repository.
	// +kubebuilder:default="dxflrs/amd64_garage"
	// +optional
	Repository string `json:"repository,omitempty"`

	// tag is the image tag. Pinned by the user; defaulted by the operator if omitted.
	// +kubebuilder:default="v2.0.0"
	// +optional
	Tag string `json:"tag,omitempty"`
}

// SecretBootstrapMode controls whether a secret value is generated by the operator
// or supplied by the user.
// +kubebuilder:validation:Enum=Generate;Provided
type SecretBootstrapMode string

const (
	// SecretBootstrapGenerate makes the operator generate the secret into a Secret it owns.
	SecretBootstrapGenerate SecretBootstrapMode = "Generate"
	// SecretBootstrapProvided makes the operator read the secret from a user-supplied Secret.
	SecretBootstrapProvided SecretBootstrapMode = "Provided"
)

// SecretKeySelector points at a single key within a Secret.
type SecretKeySelector struct {
	// name is the Secret name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// key is the key within the Secret holding the value.
	// +kubebuilder:validation:Required
	Key string `json:"key"`
}

// SecretBootstrap describes how a sensitive value (admin token, RPC secret) is sourced.
type SecretBootstrap struct {
	// mode selects Generate (operator-managed) or Provided (user-supplied via secretRef).
	// +kubebuilder:default=Generate
	// +optional
	Mode SecretBootstrapMode `json:"mode,omitempty"`

	// secretRef is the Secret to read when mode is Provided.
	// +optional
	SecretRef *SecretKeySelector `json:"secretRef,omitempty"`
}

// StorageSpec describes a single persistent volume (data or metadata) for a node pool.
type StorageSpec struct {
	// size is the requested volume size. For the data volume this also derives the
	// node's Garage layout capacity.
	// +kubebuilder:validation:Required
	Size resource.Quantity `json:"size"`

	// storageClass is the StorageClass for the volume; the cluster default is used if omitted.
	// +optional
	StorageClass *string `json:"storageClass,omitempty"`
}

// NodePoolStorage groups the data and metadata volumes for a node pool.
type NodePoolStorage struct {
	// data is the bulk object-storage volume. Its size derives the node's layout capacity.
	// +kubebuilder:validation:Required
	Data StorageSpec `json:"data"`

	// meta is the metadata-database volume.
	// +kubebuilder:validation:Required
	Meta StorageSpec `json:"meta"`
}

// NodePool is a set of identically-configured Garage nodes backed by one StatefulSet.
// Each pool maps to a single Garage zone.
type NodePool struct {
	// name uniquely identifies the pool within the cluster (used in child resource names).
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
	Name string `json:"name"`

	// replicas is the number of Garage nodes in the pool.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Required
	Replicas int32 `json:"replicas"`

	// zone is the Garage layout zone for this pool. Defaults to the pool name if omitted.
	// +optional
	Zone string `json:"zone,omitempty"`

	// storage configures the data and metadata volumes.
	// +kubebuilder:validation:Required
	Storage NodePoolStorage `json:"storage"`

	// resources sets the Garage container resource requirements.
	// +optional
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// nodeSelector constrains pods to nodes matching these labels.
	// +optional
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// tolerations allow pods to schedule onto tainted nodes.
	// +optional
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`

	// affinity sets pod scheduling affinity/anti-affinity.
	// +optional
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
}

// ServiceConfig configures how a client-facing endpoint is exposed.
type ServiceConfig struct {
	// type is the Kubernetes Service type for the endpoint.
	// +kubebuilder:default=ClusterIP
	// +optional
	Type corev1.ServiceType `json:"type,omitempty"`
}

// ServicesConfig groups the client-facing Service exposure. The admin API is
// intentionally not exposed: it is reached only over per-pod headless DNS, since some
// admin operations are node-local and load balancing would route to a random node.
type ServicesConfig struct {
	// s3Api exposes the S3 API endpoint.
	// +optional
	S3Api ServiceConfig `json:"s3Api,omitempty"`

	// web exposes the static website endpoint.
	// +optional
	Web ServiceConfig `json:"web,omitempty"`
}

// S3ApiConfig configures the Garage S3 API endpoint.
type S3ApiConfig struct {
	// region is the S3 region name advertised by Garage.
	// +kubebuilder:default="garage"
	// +optional
	Region string `json:"region,omitempty"`

	// rootDomain is the DNS suffix for virtual-hosted-style bucket access (e.g. ".s3.garage.tld").
	// +optional
	RootDomain string `json:"rootDomain,omitempty"`
}

// S3WebConfig configures the Garage static website endpoint.
type S3WebConfig struct {
	// rootDomain is the DNS suffix for website bucket access (e.g. ".web.garage.tld").
	// +optional
	RootDomain string `json:"rootDomain,omitempty"`
}

// S3Config groups the S3 API and website settings.
type S3Config struct {
	// api configures the S3 API endpoint.
	// +optional
	Api S3ApiConfig `json:"api,omitempty"`

	// web configures the static website endpoint.
	// +optional
	Web S3WebConfig `json:"web,omitempty"`
}

// GarageDBEngine selects the Garage metadata database engine.
// +kubebuilder:validation:Enum=lmdb;sqlite;fjall
type GarageDBEngine string

// GarageConsistencyMode selects the Garage read/write consistency guarantees.
// +kubebuilder:validation:Enum=consistent;degraded;dangerous
type GarageConsistencyMode string

// GarageClusterSpec defines the desired state of GarageCluster.
type GarageClusterSpec struct {
	// image selects the Garage container image.
	// +optional
	Image GarageImage `json:"image,omitempty"`

	// dbEngine selects the metadata database engine.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#db_engine
	// +kubebuilder:default=lmdb
	// +optional
	DBEngine GarageDBEngine `json:"dbEngine,omitempty"`

	// blockSize is the block size in bytes for stored objects.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#block_size
	// +kubebuilder:default=1048576
	// +kubebuilder:validation:Minimum=1
	// +optional
	BlockSize int64 `json:"blockSize,omitempty"`

	// replicationFactor is the Garage replication_factor. Immutable on a live cluster
	// (enforced by webhook in a later phase); changing it risks data loss.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#replication_factor
	// +kubebuilder:default=3
	// +kubebuilder:validation:Minimum=1
	// +optional
	ReplicationFactor int32 `json:"replicationFactor,omitempty"`

	// consistencyMode selects the read/write consistency guarantees.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#consistency_mode
	// +kubebuilder:default=consistent
	// +optional
	ConsistencyMode GarageConsistencyMode `json:"consistencyMode,omitempty"`

	// compressionLevel is the zstd compression level for stored blocks.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#compression_level
	// +kubebuilder:default=1
	// +optional
	CompressionLevel int32 `json:"compressionLevel,omitempty"`

	// metadataAutoSnapshotInterval, when set (e.g. "6h"), makes Garage snapshot its
	// metadata DB at that interval. Empty disables snapshots.
	// https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#metadata_auto_snapshot_interval
	// +optional
	MetadataAutoSnapshotInterval string `json:"metadataAutoSnapshotInterval,omitempty"`

	// nodePools defines one or more pools of Garage nodes. Each pool becomes a StatefulSet
	// and maps to a single Garage zone.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +listType=map
	// +listMapKey=name
	NodePools []NodePool `json:"nodePools"`

	// adminToken configures the Admin API token bootstrap.
	// +optional
	AdminToken SecretBootstrap `json:"adminToken,omitempty"`

	// rpcSecret configures the inter-node RPC secret bootstrap.
	// +optional
	RpcSecret SecretBootstrap `json:"rpcSecret,omitempty"`

	// services configures exposure of the S3 and web endpoints.
	// +optional
	Services ServicesConfig `json:"services,omitempty"`

	// s3 configures the S3 API and website settings.
	// +optional
	S3 S3Config `json:"s3,omitempty"`
}

// LayoutNodeStatus echoes one node's role in the applied Garage layout.
type LayoutNodeStatus struct {
	// nodeId is the Garage node identifier (its public key).
	NodeID string `json:"nodeId"`

	// pod is the Kubernetes Pod backing the node.
	Pod string `json:"pod"`

	// zone is the Garage layout zone assigned to the node.
	Zone string `json:"zone"`

	// capacity is the layout capacity assigned to the node, derived from storage.data.size.
	Capacity resource.Quantity `json:"capacity"`

	// role is the node's layout role (e.g. active).
	Role string `json:"role"`
}

// LayoutStatus reports the applied Garage cluster layout.
type LayoutStatus struct {
	// version is the applied Garage layout version.
	Version int64 `json:"version"`

	// nodes lists the per-node layout assignments.
	// +listType=atomic
	// +optional
	Nodes []LayoutNodeStatus `json:"nodes,omitempty"`
}

// HealthStatus mirrors Garage's GetClusterHealth response.
type HealthStatus struct {
	// status is one of healthy, degraded, or unavailable.
	Status string `json:"status"`

	// connectedNodes is the number of nodes currently connected.
	ConnectedNodes int `json:"connectedNodes"`

	// knownNodes is the number of nodes known to the cluster.
	KnownNodes int `json:"knownNodes"`

	// partitionsQuorum is the "<withQuorum>/<total>" partition quorum ratio.
	PartitionsQuorum string `json:"partitionsQuorum"`
}

// EndpointsStatus reports the resolved client-facing endpoints.
type EndpointsStatus struct {
	// s3Api is the S3 API endpoint URL.
	// +optional
	S3Api string `json:"s3Api,omitempty"`

	// web is the website endpoint URL.
	// +optional
	Web string `json:"web,omitempty"`
}

// GarageClusterStatus defines the observed state of GarageCluster.
type GarageClusterStatus struct {
	// conditions represent the current state of the GarageCluster resource.
	// Known types: Ready, WorkloadReady, PeersConnected, LayoutApplied.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// observedGeneration is the generation most recently reconciled into status.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// layout reports the applied Garage cluster layout.
	// +optional
	Layout *LayoutStatus `json:"layout,omitempty"`

	// health mirrors Garage's cluster health.
	// +optional
	Health *HealthStatus `json:"health,omitempty"`

	// endpoints reports the resolved client-facing endpoints.
	// +optional
	Endpoints *EndpointsStatus `json:"endpoints,omitempty"`

	// adminTokenSecret names the Secret holding the Admin API token.
	// +optional
	AdminTokenSecret string `json:"adminTokenSecret,omitempty"`

	// rpcTokenSecret names the Secret holding the RPC secret.
	// +optional
	RpcTokenSecret string `json:"rpcTokenSecret,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Layout",type=integer,JSONPath=".status.layout.version"
// +kubebuilder:printcolumn:name="Health",type=string,JSONPath=".status.health.status"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

// GarageCluster is the Schema for the garageclusters API
type GarageCluster struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of GarageCluster
	// +required
	Spec GarageClusterSpec `json:"spec"`

	// status defines the observed state of GarageCluster
	// +optional
	Status GarageClusterStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// GarageClusterList contains a list of GarageCluster
type GarageClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []GarageCluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &GarageCluster{}, &GarageClusterList{})
		return nil
	})
}
